import raw from "@/content/school.json";

/**
 * Typed accessor for the build-time content in content/school.json
 * (generated by scripts/fetch-content.mjs from the live school website).
 */

export interface Proximity {
  distance: string;
  place: string;
}
export interface KeyFactor {
  key: string;
  title: string;
  image: string;
}
export interface AdmissionStep {
  title: string;
  body: string;
}
export interface Testimonial {
  quote: string;
  name: string;
  role: string;
}
export interface Campus {
  name: string;
  status: string;
}
export interface Programme {
  title: string;
  image: string;
  body: string;
}
export interface BeyondItem {
  title: string;
  image: string;
}
export interface StatItem {
  value: number;
  suffix: string;
  label: string;
  displayValue: string | null;
}
export interface TrustItem {
  label: string;
  value: string;
}

export interface SchoolContent {
  generatedAt: string;
  source: Record<string, string>;
  _livePages?: number;
  school: {
    name: string;
    location: string;
    trust: string;
    chairman: string;
    board: string;
    affiliationNo: string;
    type: string;
    tagline: string;
  };
  hero: {
    eyebrow: string;
    headline: string;
    headlineLines: string[];
    subhead: string;
    intro: string;
  };
  welcome: {
    heading: string;
    subheading: string;
    paragraphs: string[];
  };
  about: {
    coreMotive: string;
    locationCopy: string;
    proximity: Proximity[];
  };
  philosophy: {
    heading: string;
    statement: string;
    values: { name: string; body: string }[];
  };
  keyFactors: KeyFactor[];
  admissions: {
    heading: string;
    intro: string;
    ageCriterion: string;
    steps: AdmissionStep[];
    rejectionPolicy: string;
    antiDonation: string;
  };
  testimonials: Testimonial[];
  growingGroup: {
    heading: string;
    intro: string;
    campuses: Campus[];
  };
  programmes: {
    heading: string;
    subheading: string;
    items: Programme[];
  };
  beyondCurriculum: {
    heading: string;
    eyebrow: string;
    items: BeyondItem[];
  };
  contact: {
    phones: string[];
    email: string;
    addressLines: string[];
    officeHours: string;
    mapsEmbed: string;
    mapsLink: string;
  };
  social: {
    facebook: string;
    instagram: string;
    youtube: string;
    linkedin: string;
  };
  images: {
    logo: string;
    logoMark: string;
    campus: string;
    heroPhoto: string;
    heroCarousel: string[];
    aboutPhoto: string;
    whyPhoto: string;
    banners: string[];
  };
  gradeOptions: string[];
  stats: {
    editable: boolean;
    note: string;
    items: StatItem[];
  };
  trustStrip: TrustItem[];
}

export const content = raw as unknown as SchoolContent;

/** Digits-only phone for tel: / wa.me links */
export const telHref = (phone: string) => `tel:+91${phone.replace(/\D/g, "")}`;
export const waHref = (phone: string, text: string) =>
  `https://wa.me/91${phone.replace(/\D/g, "")}?text=${encodeURIComponent(text)}`;
